---
# - name: Show facts available on the system
#   ansible.builtin.debug:
#     var: ansible_facts

- name: Set proxy environment variables
  ansible.builtin.set_fact:
    http_proxy: lookup('ansible.builtin.env', 'http_proxy')
    https_proxy: lookup('ansible.builtin.env', 'http_proxy')
    no_proxy: lookup('ansible.builtin.env', 'no_proxy')

- name: package install if redhat
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat' or ansible_facts['distribution_file_variety']|lower == 'redhat'

- name: package install if debian
  import_tasks: debian.yml
  when: ansible_facts['distribution']|lower == 'debian'

- name: package install if ubuntu
  import_tasks: ubuntu.yml
  when: ansible_facts['distribution']|lower == 'ubuntu'

- name: ocp tools install
  import_tasks: ocp_tools.yml
