---
- name: Check if kubectl client is installed
  ansible.builtin.command: which kubectl
  register: ocp_kubectl_check
  ignore_errors: true
  changed_when: false

- name: Check if oc_cli client is installed
  ansible.builtin.command: which oc
  register: ocp_cli_check
  ignore_errors: true
  changed_when: false

- name: Install kubectl and OC tools
  import_tasks: ocp_tool_kubectl.yml
  when: ocp_cli_check.rc != 0 or ocp_kubectl_check.rc != 0 

- name: Check if helm client is installed
  ansible.builtin.command: which helm
  register: ocp_helm_check
  ignore_errors: true
  changed_when: false

- name: Install Helm tool
  import_tasks: ocp_tool_helm.yml
  when: ocp_helm_check.rc != 0

- name: Check if tkn client is installed
  ansible.builtin.command: which tkn
  register: ocp_tkn_check
  ignore_errors: true
  changed_when: false

- name: Install tkn tool
  import_tasks: ocp_tool_tekton.yml
  when: ocp_tkn_check.rc != 0

- name: Check if stern client is installed
  ansible.builtin.command: which stern
  register: ocp_stern_check
  ignore_errors: true
  changed_when: false

- name: Install stern tool
  import_tasks: ocp_tool_github.yml
  when: ocp_stern_check.rc != 0
  vars:
    owner: stern
    repo: stern
    asset_name_filter: linux_amd64

- name: Check if kubectl-neat client is installed
  ansible.builtin.command: which kubectl-neat
  register: ocp_kneat_check
  ignore_errors: true
  changed_when: false

- name: Install kubectl-neat tool
  import_tasks: ocp_tool_github.yml
  when: ocp_kneat_check.rc != 0
  vars:
    owner: itaysk
    repo: kubectl-neat
    asset_name_filter: linux_amd64

- name: Check if argocd client is installed
  ansible.builtin.command: which argo-cd
  register: ocp_argocd_check
  ignore_errors: true
  changed_when: false

- name: Install argocd tool
  import_tasks: ocp_tool_github_argo.yml
  when: ocp_argocd_check.rc != 0
  vars:
    owner: argoproj
    repo: argo-cd
    asset_name_filter: linux-amd64

- name: Check if kubeseal client is installed
  ansible.builtin.command: which kubeseal
  register: ocp_kubeseal_check
  ignore_errors: true
  changed_when: false

# Filter update
- name: Install kubeseal tool
  import_tasks: ocp_tool_github_kubeseal.yml
  when: ocp_kubeseal_check.rc != 0
  vars:
    owner: bitnami-labs
    repo: sealed-secrets
    asset_name_filter: linux-amd64.tar.gz

# - name: Check if sops client is installed
#   ansible.builtin.command: which sops
#   register: ocp_sops_check
#   ignore_errors: true
#   changed_when: false

# - name: Install sops tool
#   import_tasks: ocp_tool_github_argo.yml
#   when: ocp_sops_check.rc != 0
#   vars:
#     owner: getsops
#     repo: sops
#     asset_name_filter: linux.amd64

# - name: Check if aws client is installed
#   ansible.builtin.command: which aws
#   register: ocp_awscli_check
#   ignore_errors: true
#   changed_when: false

# removed vars as there is issue in scope. Not sure why? :(
# - name: Install aws cli tool
#   import_tasks: ocp_tool_awscli.yml
#   when: ocp_awscli_check.rc != 0

# - name: Check if gh client is installed
#   ansible.builtin.command: which gh
#   register: ocp_ghcli_check
#   ignore_errors: true
#   changed_when: false

# - name: Install gh tool
#   import_tasks: ocp_tool_github_ghcli.yml
#   when: ocp_ghcli_check.rc != 0
#   vars:
#     owner: cli
#     repo: cli
#     asset_name_filter: linux_amd64.tar.gz