---

- name: Download helm
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/clients/helm/latest/helm-linux-amd64 
    dest: /tmp/helm-linux-amd64

- name: Copy file with owner and permissions
  become: true
  become_method: sudo
  ansible.builtin.copy:
    src: /tmp/helm-linux-amd64
    dest: /usr/local/bin/helm
    owner: root
    group: root
    mode: '0755'

- name: Get helm version
  command: /usr/local/bin/helm version
  register: helm_version
  changed_when: false

- name: Print helm version
  debug:
    msg: "helm version: {{ helm_version.stdout }}"
