---
# tasks file

- name: Install packages
  become: true
  become_method: sudo
  ansible.builtin.apt:
    name:
      - dos2unix
      - jq
      - neofetch
      - unzip
      - tree
      - podman
    state: present
